// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvwzggnbrspprmlfrfud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2d3pnZ25icnNwcHJtbGZyZnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTgxNDMsImV4cCI6MjA2NTE5NDE0M30.8Sa7jI3iIABsXkVI8O8K5TIRF9qhCxLOiI6-xrdUcnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);